#!/usr/bin/env python3
"""Generate a digest-only Supabase guest-group seed from the private CSV."""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
import unicodedata
from collections import defaultdict
from pathlib import Path


HEADER_CODE_NAMES = {
    "code",
    "access code",
    "access_code",
    "guest code",
    "guest_code",
}


def normalize_code(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "", value).upper()


def normalize_name(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", value)
    return " ".join(normalized.split()).casefold()


def load_groups(csv_path: Path) -> dict[str, int]:
    groups: dict[str, set[str]] = defaultdict(set)
    raw_codes: dict[str, set[str]] = defaultdict(set)

    with csv_path.open(newline="", encoding="utf-8-sig") as source:
        rows = list(csv.reader(source))

    if rows and len(rows[0]) >= 2 and rows[0][1].strip().casefold() in HEADER_CODE_NAMES:
        rows = rows[1:]

    for row_number, row in enumerate(rows, start=1):
        if len(row) < 2:
            raise ValueError(f"row {row_number}: expected at least two columns")

        name = normalize_name(row[0])
        code = normalize_code(row[1])
        if not name or not code:
            raise ValueError(f"row {row_number}: guest name and access code are required")
        if len(code) > 128:
            raise ValueError(f"row {row_number}: normalized access code is too long")

        groups[code].add(name)
        raw_codes[code].add(row[1].strip())

    collisions = [code for code, values in raw_codes.items() if len(values) > 1]
    if collisions:
        raise ValueError(
            "multiple raw codes normalize to the same value; resolve the CSV collision first"
        )

    counts = {code: len(names) for code, names in groups.items()}
    if not counts:
        raise ValueError("the CSV contains no guest groups")
    if any(count < 1 or count > 50 for count in counts.values()):
        raise ValueError("every guest group must have between 1 and 50 unique names")
    return counts


def render_seed(counts: dict[str, int], source_name: str) -> str:
    values = []
    for code, count in sorted(counts.items()):
        digest = hashlib.sha256(code.encode("ascii")).hexdigest()
        values.append(f"  ('{digest}', {count})")

    return f"""-- Generated by supabase/scripts/generate_guest_group_seed.py.
-- Source: {source_name} (private and gitignored).
-- Contains only SHA-256 code digests and deterministic unique-name counts.

create temporary table guest_group_import (
  code_digest text primary key check (code_digest ~ '^[0-9a-f]{{64}}$'),
  allowed_slots integer not null check (allowed_slots between 1 and 50)
) on commit drop;

insert into guest_group_import (code_digest, allowed_slots)
values
{',\n'.join(values)};

-- The private CSV is authoritative. Removed groups and their RSVP slots are
-- deleted through the guests foreign key's ON DELETE CASCADE behavior.
delete from public.invites as invitation
where not exists (
  select 1
  from guest_group_import as imported
  where imported.code_digest = invitation.code_digest
);

insert into public.invites (
  code_digest,
  num_seats,
  access_enabled
)
select
  imported.code_digest,
  imported.allowed_slots,
  true
from guest_group_import as imported
on conflict (code_digest) do update
set num_seats = excluded.num_seats,
    access_enabled = true;

-- Reconcile exactly one database row per allowed slot without importing CSV
-- names. Existing submitted rows within the allowed range are preserved.
insert into public.guests (invite_id, seat_number)
select invitation.id, slot.seat_number
from public.invites as invitation
cross join lateral generate_series(1, invitation.num_seats) as slot(seat_number)
where invitation.access_enabled
on conflict (invite_id, seat_number) do nothing;

delete from public.guests as guest
using public.invites as invitation
where guest.invite_id = invitation.id
  and invitation.access_enabled
  and guest.seat_number > invitation.num_seats;

do $$
begin
  if exists (
    select 1
    from public.invites as invitation
    left join public.guests as guest
      on guest.invite_id = invitation.id
     and guest.seat_number between 1 and invitation.num_seats
    where invitation.access_enabled
    group by invitation.id, invitation.num_seats
    having count(guest.id) <> invitation.num_seats
  ) then
    raise exception 'GUEST_GROUP_SLOT_RECONCILIATION_FAILED';
  end if;
end;
$$;
"""


def render_admin_import(counts: dict[str, int], source_name: str) -> str:
    values = [f"  ('{code}', {count})" for code, count in sorted(counts.items())]

    return f"""-- Generated from {source_name}; keep this file private.
-- Run after the rsvp_invite_admin migration to make dashboard codes readable.
-- It contains plaintext invitation codes and must not be committed.

insert into public.rsvp_invite_admin (invite_code, reserved_seats)
values
{',\n'.join(values)}
on conflict (invite_code) do update
set reserved_seats = excluded.reserved_seats,
    access_enabled = true;
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--admin-output",
        type=Path,
        help="optional private SQL import for the readable dashboard table",
    )
    args = parser.parse_args()

    counts = load_groups(args.input)
    output = render_seed(counts, args.input.name)
    args.output.write_text(output, encoding="utf-8")
    print(f"wrote {len(counts)} digest-only guest groups to {args.output}")

    if args.admin_output:
        admin_output = render_admin_import(counts, args.input.name)
        args.admin_output.write_text(admin_output, encoding="utf-8")
        print(f"wrote {len(counts)} private dashboard groups to {args.admin_output}")


if __name__ == "__main__":
    main()
